accepted = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "GPL-3.0",
    "MIT",
    "WTFPL",
]

targets = [
    "x86_64-unknown-linux-gnu",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
